# BATCH DB — THE ONE AUTHORED BATTLE FIXTURE, AND THE ONE AUTHORED TALLY.
#
# `_spawn` was copied into SEVEN gates as FOUR divergent bodies and it cost
# twice before anyone consolidated it: the copied `_report` drifted into FOUR
# print shapes (two of them countless), and CQ §1's deliberate removal of two
# `Profile.set_flag` lines from one copy left them standing in FIVE others with
# nothing anywhere reporting the divergence. DA §3 swept, named it, and ruled
# that consolidating it was its own batch. This is that batch.
#
# ── WHY THIS IS A `preload`ed RefCounted AND NOT A BASE CLASS ────────────────
# The obvious shape is `extends GateBase` so every gate inherits `ok`, `_report`
# and `_spawn` with ZERO call sites changed. **IT DOES NOT WORK, AND IT FAILS
# SILENTLY.** A `--script` SceneTree target cannot resolve its own base class:
#
#     Parse Error: Could not find base class "GateBase"   → and the process
#     Parse Error: Could not resolve class "res://..."     EXITS 0.
#
# Both spellings — `extends GateBase` and `extends "res://gate_base.gd"` — fail,
# with the global class cache present and correct. Measured, not assumed.
#
# ── AND WHY THIS FILE CARRIES NO `class_name` ───────────────────────────────
# `class_name` registration lives in `.godot/global_script_class_cache.cfg`,
# which is GITIGNORED and is only regenerated by an editor pass. A `class_name`
# added here would resolve on this machine and fail on a fresh clone. Consumers
# `preload` it BY PATH, which needs no cache and cannot rot.
#
# ── THE AUTOLOAD RULE, WHICH THIS FILE IS BOUND BY (CT, CLAUDE.md) ──────────
# A `--script` harness can only compile files that name no autoload, and this
# file is compiled as a dependency of seven of them. The project's autoloads are
# exactly `Run`, `Settings` and `Music` — so **`Run` IS NEVER NAMED HERE**; it is
# fetched at RUNTIME off the caller's tree by string path. `Talents` and
# `Profile` are `class_name` globals, not autoloads, and are safe to name.
# CLAUDE.md's rule text lists `Talents`, `Classes`, `Relics` and `Profile`
# alongside `Run` as unsafe; four of those five are script classes and are not.
extends RefCounted

# ── THE FIXTURE ─────────────────────────────────────────────────────────────

# The party every gate builds, and the encounter every gate fights. Authored
# once. `opts` carries the three differences the seven copies legitimately had:
#
#   deterministic : bool  — force the damage roll (check_cm_live, check_cs).
#                           The AK/AL/AR discipline: a blocked, parried or
#                           critical blow would swamp a 15% difference.
#                           `block_chance = 0.0` IS NOT ENOUGH ON A WARDEN —
#                           `_live_block_chance` adds `_plating_slice` on top of
#                           the field and the sum is clamped to [0,1], so a large
#                           negative field is what actually turns the roll off.
#   items         : Dict  — pre-load the pouch (check_ct). A HELD, EMPTY SLOT
#                           goes in deliberately: "the pouch renders full and
#                           empty" and empty only exists because a drained stack
#                           keeps its slot.
#   run           : Node  — supply the run node instead of fetching it
#                           (check_ct already holds it).
#
# THE `Profile.set_flag` LINES ARE GONE AND THEY ARE NOT COMING BACK — see
# `flags_are_inert()` below for the proof, which is asserted rather than argued.
static func spawn(tree: SceneTree, specs: Array, opts: Dictionary = {}) -> Node:
	var root: Node = tree.root
	var run: Node = opts.get("run", null)
	if run == null:
		run = root.get_node("/root/Run")
	run.sim_run = false
	run.new_run(["warrior", "mage", "cleric", "hunter"], [], "standard")
	for i in run.party.size():
		run.party[i]["spec"] = specs[i]
		run.party[i]["tree"] = Talents.generate_tree(specs[i], run.party[i]["key"])
		run.party[i]["runes"] = []
		run.party[i]["talents"] = {}
		run.sync_spec_hp(i)
	run.specs_chosen = true
	run.active = true
	var items: Dictionary = opts.get("items", {})
	for k in items:
		run.items[k] = items[k]
	run.encounter = {"type": "fight", "theme": "Warband",
		"enemies": ["raider", "raider", "archer"]}
	OS.set_environment("DOD_AUTOPLAY", "")
	OS.set_environment("DOD_ENEMIES_OFF", "1")
	var scene: Node = load("res://scenes/battle.tscn").instantiate()
	root.add_child(scene)
	Engine.time_scale = 50.0
	for _i in 90:
		await tree.process_frame
	Engine.time_scale = 1.0
	if bool(opts.get("deterministic", false)):
		for u in scene.get("heroes") + scene.get("enemies"):
			u.no_cover = 1
			u.parry_chance = 0.0
			u.block_chance = -10.0
			u.crit_bonus = -1.0
	return scene


# THE RULING THAT DECIDED THE MERGE, ASSERTED RATHER THAN ARGUED.
#
# Five gates hand-set `skill_check_taught` and `defensive_check_taught`; two did
# not. Merging had to pick one, and §0 forbids picking the newest or the fullest.
# The flags are DEAD under every gate, and this function is why:
#
#   `battle._nobody_can_press()` is `sim or autoplay or headless`, and a gate is
#   always `--headless`. The only two call sites are
#     · `_run_skill_check`:  `if not _nobody_can_press() and ...` → never entered,
#                            so the flags are never READ; and
#     · `_resolve` (defensive): `if _nobody_can_press()` → the bot branch.
#   No gate asserts on either flag. Their ONE live effect was `Profile._save()`
#   writing `user://profile.json` on every gate run — a gate mutating the
#   player's profile, which is the opposite of what `check_ct` promises when it
#   asserts it leaves the save as it found it.
#
# So the flags are omitted, which is CQ §1's ruling applied to the other five
# copies. A gate calls this to assert the ground it stands on, so the day
# `_nobody_can_press()` stops covering headless, the gates say so instead of
# quietly measuring a bot mix.
# ── BATCH DW — THE SOURCE SCANNER, AUTHORED ONCE ────────────────────────────
# `check_da` §3 and `check_dw` both need to read a .gd file as FUNCTION BODIES
# rather than as one string, and DA/DB/DD's whole lesson is that the second
# copy of a helper is where the two copies start to disagree. It lives here for
# the same reason `spawn` does.
#
# **COMMENTS ARE STRIPPED FIRST, AND THAT IS THE LOAD-BEARING HALF.**
# `check_ds` took a red out of §3 for a HEADER COMMENT that named two accessors
# while explaining that the file does not call them, and the ruling then was
# that an exemption granted to a SENTENCE blinds the rule to a real walk
# arriving in that file later. Stripping is that ruling made mechanical: prose
# describing a walk is not a walk.
static func strip_comments(src: String) -> String:
	var out := ""
	for raw_line in src.split("\n"):
		var line := String(raw_line)
		var quote := ""
		var kept := ""
		var i := 0
		while i < line.length():
			var c := line[i]
			if quote != "":
				if c == "\\":
					kept += line.substr(i, 2)
					i += 2
					continue
				if c == quote:
					quote = ""
				kept += c
			elif c == "\"" or c == "'":
				quote = c
				kept += c
			elif c == "#":
				break
			else:
				kept += c
			i += 1
		out += kept + "\n"
	return out


# Every `func` body in a file as {name: body}, with the VOID ones dropped — a
# function that returns nothing is asserting, not enumerating. An UNANNOTATED
# `func` counts as returning, because that is the permissive direction: the
# cost of looking at one extra body is a sentence, and the cost of skipping one
# is the defect `check_da` §3 exists for.
static func returning_bodies(src: String) -> Dictionary:
	var lines := strip_comments(src).split("\n")
	var starts: Array = []
	for i in lines.size():
		if String(lines[i]).begins_with("func "):
			starts.append(i)
	var out := {}
	for n in starts.size():
		var a: int = starts[n]
		var b: int = starts[n + 1] if n + 1 < starts.size() else lines.size()
		var head := String(lines[a])
		if head.contains("-> void"):
			continue
		var fname := head.substr(5, head.length() - 5)
		var paren := fname.find("(")
		if paren >= 0:
			fname = fname.substr(0, paren)
		var body := ""
		for k in range(a, b):
			body += String(lines[k]) + "\n"
		out[fname.strip_edges()] = body
	return out


static func flags_are_inert(scene: Node) -> bool:
	return bool(scene.call("_nobody_can_press"))


# ── THE TALLY ───────────────────────────────────────────────────────────────
# Instance state, because a count belongs to one gate's run. `ok()` and
# `report()` were copied seven ways too: FOUR gates' `ok()` never incremented a
# check counter at all, so `check_cm_live`, `check_co`, `check_cy` and `check_cz`
# could only ever print a failure count — and `run_battery.sh` showed `checks=?`
# for all four, which is the one thing a count-diffing rule cannot read.
var checks := 0
var fails := 0


func ok(cond: bool, what: String) -> void:
	checks += 1
	if not cond:
		fails += 1
		print("  FAIL: %s" % what)


# ONE SHAPE, AND IT IS THE SLASH. The comma shape is the one `run_battery.sh`'s
# header records as a scar (`grep -E "checks,"` missed every suite that printed
# no comma). THE BATTERY'S GREP IS **NOT** NARROWED BACK TO ONE FORMAT — see
# `docs/reports/DB.md` §1: it also serves 45 SUITES that print four other shapes,
# and CS already had to widen it a third time. One shape for the GATES; a grep
# that reads them all for the battery.
#
# The name is derived from the script's own path rather than written in, because
# a hand-written name is the next thing to drift: `check_cs` printed `check_cs`
# only because nobody had yet copied that line into a gate called something else.
func report(tree: SceneTree) -> void:
	var s: Script = tree.get_script() as Script
	var name := "gate"
	if s != null and s.resource_path != "":
		name = s.resource_path.get_file().get_basename()
	print("%s: %d checks / %d failures" % [name, checks, fails])
	tree.quit(1 if fails > 0 else 0)
